"""Deterministic mock implementation of the LLMAdapter interface.

Lets the rest of the application run end-to-end without network access or
a Groq API key, by returning fixed, schema-shaped sample data instead of
calling a real LLM provider.
"""

from llm.adapter import LLMAdapter


class MockAdapter(LLMAdapter):
    """LLMAdapter implementation that returns deterministic sample data."""

    def extract(self, text: str) -> dict:
        """Return a fixed dictionary shaped like a real extraction response.

        Args:
            text: The raw supplier quote text. Ignored by this adapter, but
                accepted to satisfy the LLMAdapter interface.

        Returns:
            A deterministic, unvalidated dictionary matching the expected
            extraction shape.
        """
        return {
            "supplier_name": "Acme Supply Co.",
            "currency": "USD",
            "items": [
                {
                    "sku": "SKU-1001",
                    "description": "Stainless steel bracket",
                    "quantity": 100,
                    "unit_price": 4.25,
                    "lead_time_days": 14,
                },
                {
                    "sku": None,
                    "description": "Custom mounting plate",
                    "quantity": 25,
                    "unit_price": 12.5,
                    "lead_time_days": None,
                },
            ],
            "quote_expiry": "2026-08-15",
            "shipping_included": False,
            "notes": ["Mock response generated by MockAdapter."],
            "assumptions": ["Lead time for the custom mounting plate was not stated."],
            "needs_review": True,
        }
